#let qs(body) = {
  set enum(numbering: "(a)")
  set par(justify: true)
  body
  v(0.5em)
}
#let pt(body) = {
  body
}
#align(center)[
  *DMML*\ 7. gyakorlat (2025-11-06)\ _VC-dimenzió_
]

#set document(
  author: "Apagyi Dávid",
  title: "DMML 7. gyakorlat",
  date: datetime(year: 2025, month: 11, day: 6, hour: 10, minute: 10, second: 0),
)
#set text(lang: "hu")

= Feladatok

+ #qs[
    + #pt[
        $cal(X) = RR^2$, $cal(F) = {"lineáris klasszifikátorok"}$, azaz $cal(H) = {"félsíkok"}$.
      ]
    + #pt[
        $cal(X) = RR^d$, $cal(F) = {"lineáris klasszifikátorok"}$.
      ]
  ]
+ #qs[
    Igazoljuk, hogy ha $cal(H)$ véges, akkor $dim_"VC" (cal(H)) <= log_2 |cal(H)|$.
  ]
+ #qs[
    $cal(X) = {1,2,..., 999}$, $cal(C) = {C_0, C_1, ..., C_9}$, ahol $C_i$ azokból az $n in cal(X)$ számokból áll, amelyek tízes számrendszerbeli leírása tartalmazza az $i$ számjegyet. Mennyi $dim_"VC" (cal(C))$?
  ]
+ #qs[
    + #pt[
        $cal(X) = RR^2$, $cal(H) = {"tengelypárhuzamos téglalapok"}$.
      ]
    + #pt[
        $cal(X) = RR^(d)$, $cal(H) = {"tengelypárhuzamos téglák"}$.
      ]
  ]
+ #qs[
    + #pt[
        $cal(X) = RR$, $cal(F) = { f_(a,b)(x) = II(a <= x <= b) : a,b in RR}$, azaz $cal(H) = {"intervallumok"}$.
      ]
    + #pt[
        ("Előjeles intervallumok.") $cal(X) = RR$, $cal(F) = { f_(a,b,s) : a,b in RR, s in {-1,1}}$, ahol:
        $ f_(a,b,s) (x) = cases(s\, &"ha" x in [a,b], -s\, #h(1em)&"ha" x in.not [a,b]) $
      ]
  ]
+ #qs[
    + #pt[
        Legyen $k<=|cal(X)|<infinity$, $cal(H)_(<=k) = { H subset.eq cal(X) : |H| <= k }$. Mennyi $dim_"VC" (cal(H)_(<=k))$?
      ]
    + #pt[
        Legyen $k<=|cal(X)|<infinity$, $cal(H)_(=k) = { H subset.eq cal(X) : |H| = k }$. Mennyi $dim_"VC" (cal(H)_(=k))$?
      ]
  ]
+ #qs[
    Legyen $cal(X)={0,1}^n$. Definiáljuk minden $I subset.eq {1,2,...,n}$ részhalmazra az $f_I$ paritásfüggvényt a következő módon:
    $ f_I (x_1, x_2, ..., x_n) = (sum_(i in I) x_i) mod 2. $
    Mennyi a paritásfüggvényekből álló osztály VC-dimenziója?
  ]

= VC-dimenzió

_Előadáson (Csáji Balázs Csanád):_
- A class of sets $cal(C)$ _shatters_ a set $A$ if $ forall S subset.eq A : exists C in cal(C) : S = A inter C. $
- A _class of classifiers_ $cal(F)$ shatters a set $A subset.eq cal(X)$, if the class generated by $cal(F)$, i.e., $ cal(C)_cal(F) = { C subset.eq cal(X) : exists f in cal(F) : C = f^(-1)({1})}, $ shatters $A$.
- The _Vapnik--Chervonenkis_ (VC) dimension of $cal(F)$ is the largest $h$, such that there is a set $A$ with $|A| = h$ that is shattered by $cal(F)$.

_Halmazrendszerekkel (Hajnal Péter):_
- Legyen $cal(H)$ egy halmazrendszer a $V$ halmaz felett. $A subset.eq V$ esetén $cal(H)$ nyoma $A$-ban
$ tr_A (cal(H)) = {H inter A: H in cal(H)}. $
- Egy $cal(H)$ halmazrendszer alaphalmazának egy $A$ részhalmazát _teljesnek_ nevezzük, ha $tr_A (cal(H)) = 2^A.$
- Egy $cal(H)$ halmazrendszer _Vapnyik--Cservonyenszkisz-dimenziója_ $ dim_"VC" (cal(H)) = max{|U| : U subset.eq V "teljes"}. $
